task:
  name: "Chime Titan"
  trigger_type: manual
  timeout_in: 1h
  container:
      image: nexgang/ubuntu:latest
      cpu: 8
      memory: 32G
      
  setup_script:
    - ln -fs /usr/share/zoneinfo/Asia/Jakarta /etc/localtime && date
    - cd KernelSU
    - git checkout main
    - git rev-list --count HEAD
    - patch -p1 < 10_enable_susfs_for_ksu.patch
    - cd ..
